services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - ./database/db_schema:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql