name: csc342project

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      # Make the DB accessible from outside of the Docker network if needed
      - 3307:3306
    volumes:
      # Mount a volume for mariadb's persistent files for lifecycle outside of stack
      - "./database/data:/var/lib/mysql"
      # Mount the db_schema directory into the container to be auto-read and created in the new db
      - "./database/db_schema:/docker-entrypoint-initdb.d"
    env_file:
      - .env

  api:
    build: ./api
    restart: unless-stopped
    volumes:
      - ./api/src:/app/src
      - shared-plants:/app/frontend/public/plants
    environment:
      - PORT=80
    env_file:
      - .env

  frontend:
    # build: ./frontend
    # restart: unless-stopped
    # volumes:
    #   - ./frontend/src:/app/src
    #   - ./frontend/public:/app/public
    #   - ./frontend/tailwind.config.js:/app/tailwind.config.js
    #   - shared-plants:/app/public/plants
    # environment:
    #   - PORT=80
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - PORT=80

volumes:
  shared-plants:
    # =========================================

