name: csc342

services:
  proxy:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/default.conf.template:/etc/nginx/templates/default.conf.template
    ports:
      - "80:80"

  mp1:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./MiniProject1:/usr/local/apache2/htdocs

  mp2:
    image: httpd:latest
    restart: unless-stopped
    volumes:
      - ./MiniProject2:/usr/local/apache2/htdocs
  
  mp3:
    build: ./MiniProject3/
    restart: unless-stopped
    volumes:
      - ./MiniProject3/server.js:/app/server.js
      - ./MiniProject3/static:/app/static
      - ./MiniProject3/static/uploads:/app/static/uploads
      - ./MiniProject3/templates:/app/templates
      - ./MiniProject3/validation.js:/app/validation.js

  mp4:
    build: ./MiniProject4/
    restart: unless-stopped
    volumes:
      - ./MiniProject4/server.js:/app/server.js
      - ./MiniProject4/static:/app/static
      - ./MiniProject4/templates:/app/templates
      - ./MiniProject4/src:/app/src

  mp5:
    build: ./MiniProject5/
    restart: unless-stopped
    volumes:
      - ./MiniProject5/server.js:/app/server.js
      - ./MiniProject5/static:/app/static
      - ./MiniProject5/templates:/app/templates
      - ./MiniProject5/src:/app/src