INSERT INTO `plantpal`.`Profiles` (
        `name`,
        `image`,
        `water`,
        `sun`,
        `soil`,
        `temp`,
        `info`,
        `tags`
    )
VALUES (
        'Tomato',
        'tomato.jpg',
        1.5,
        6,
        6.0,
        70,
        'Tomatoes are a garden favorite and the most popular homegrown vegetable. The fruits come in various colors from yellow to red to purple and size small to large.  Tomatoes are grown as an annual, but in frost-free climates, they are perennials. The plants can grow 3 to 10 feet tall and 1 to 4 feet wide. The plant usually has glandular hairs that are very "sticky." While the portion eaten is botanically a fruit, tomatoes are considered a vegetable due to their savory flavor. All green parts of the tomato plant are poisonous. They are in the Solanaceae or nightshade family which includes potatoes, eggplants, and peppers.Tomatoes are native to Peru, but they have spread worldwide after the Spanish colonization. China is the largest tomato-producing country, followed by the United States, Turkey, India, and Italy.The genus name, Solanum, is the Latin word, solamen, which means "comforting or soothing."  The species name, lycopersicum, means "wolf peach." Tomatoes were called "wolf peaches" when they came to Europe. This originated from a German legend that witches and sorcerers used the fruits in potions to turn themselves into werewolves. The word "tomato" originates from the Spanish word tomate. The French call the tomato. the pomme d''amour or ''Love Apple," because they believed it was an aphrodisiac.',
        '["Solanaceae", "Annual", "Edible", "Vegetable", "High-Maintenance", "Spreading"]'
    ),
    (
        'Carrot',
        'carrot.jpg',
        2.0,
        6,
        7.0,
        50,
        'Carrots are a commonly cultivated, cool-season vegetable in the carrot family (Apiaceae) and are native to central Asia and Afghanistan. They are closely related to other aromatic herbs such as parsley, fennel, and dill and most easily recognized by their feathery green leaves that protrude from a thick, fleshy, edible taproot. Carrots are most commonly orange, although cultivars in many colors and shapes are available. Their orange color is due to a high beta-carotene content, providing a significant source of vitamin A. In nature, carrots are biennials (flowering in their second year and then dying), but they are grown as annuals when harvested as a vegetable.Carrots grow best in full sun, tolerating partial shade, and moist, neutral to slightly acidic, sandy loams. Heavy, compacted, and poorly drained clay soils can cause the roots to branch and distort. Keep the soil moist, as under-watering can lead to tough, bitter carrots. Check the soil moisture several inches down rather than just the top inch. Be mindful when fertilizing, as too much nitrogen can cause the plant to divert energy towards leaf growth instead of roots.When planting, direct seeding is best—transplanting can easily damage the young taproots. In North Carolina, the best times to plant are early February to late March for a spring crop and August to mid-September for a fall crop, once temperatures are between 40 and 60 F. Row covers can help protect young seedlings from extreme heat. Bury seeds a quarter inch deep and thin plants 2 to 3 inches apart. The seeds can take up to 3 weeks to germinate and therefore can be planted before the last frost date. The roots grow to maturity between 70 to 120 days depending on cultivar and environment. They can be harvested and eaten at any time after reaching full size, about when the top of the root begins to rise out of the soil. ',
        '["Apiaceae", "Annual", "Edible", "Vegetable", "Low-Maintenance", "Arching"]'
    ),
    (
        'Cucumber',
        'cucumber.jpg',
        1.5,
        6,
        7.0,
        75,
        'Cucumber is an annual climbing or spreading vine and common vegetable grown for its crisp, green fruit. It is a member of the Cucurbitaceae (gourd) family, and its native growing region is Himalaya to northern Thailand. Cucumber plants can grow 8 to 18 inches high and 3 to 8 feet wide. If given proper soil and water, cucumber plants can be an incredibly prolific addition to your vegetable garden.Cucumber grows best in full sun and moist, rich, well-drained soil. It prefers a slightly acidic pH. It has high water needs and requires consistent moisture for proper growth, but good drainage is also important. Keep the leaves dry while watering to prevent fungal diseases. Note that vertically grown cucumber plants lose moisture more easily. Propagate cucumber by seed.Cucumber needs warm soil temperatures to germinate and grow. Seeds can be directly sown after the last frost or started indoors three to six weeks before transplanting, or less than four weeks before the last frost date. Be careful to avoid damaging the plant''s taproot when transplanting. Cucumbers can be harvested green when they reach their preferred size; however, cucumbers that have turned yellow are over ripe and will be tough and difficult to eat. Poor pollination may lead to misshapen fruit. To pick, cut the stem attaching the fruit to the vine with a sharp, clean knife or clippers. Harvest often to spur further fruit production. ',
        '["Cucurbitaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Climbing"]'
    ),
    (
        'Basil',
        'basil.jpg',
        1.0,
        6,
        6.0,
        65,
        'Sweet basil is an herb in the Lamiaceae (mint) family and native to the tropical regions of Africa and Asia. Thai and Genovese basil are cultivars of this plant. The fragrant edible leaves are great in soups, stews, and other meat dishes. Sweet basil prefers full sun and moist, well-drained soils. It can be grown from seed or is easily transplanted and should be done so after the last frost. Prune by pinching the tips of long stems and any flower buds. This promotes a branching, bushy form.Sweet basil cultivars with showy purple foliage are often used as ornamentals and are perfect for containers. Plant in a bed or window box to create contrasting colored foliage. Miniature varieties are also available, which are great for mass plantings along the edge of flower beds. ',
        '["Lamiaceae", "Annual", "Edible", "Herb", "Low-Maintenance", "Ascending"]'
    ),
    (
        'Lettuce',
        'lettuce.jpg',
        1.5,
        5,
        6.5,
        60,
        'Lactuca is a genus of wild and domesticated lettuce species, an annual in the Asteraceae family and native to various parts of the world, including sections of the United States and Canada. Several species of lettuce (L. floridana and L. sativa) are common in nurseries and landscapes and are very similar to sowthistle (Sonchus spp.). These species are annuals that prefer cool weather planting, but may also germinate in the spring or summer in irrigated nursery crops or landscapes. L. sativa, in particular, is a domesticated species familiar to home gardeners and includes the romaine, butter head, iceberg, and loose leaf lettuce types.The genus name comes from the Latin word lac meaning milk in obvious reference to the milky plant sap.Lettuce is best grown in moist to wet soils in part shade to full shade, although some species such as L. sativa prefer full sun. The plants require constant moisture. They will remain in the wild by self-seeding and to control the spread of the plant, you should avoid letting plants go to seed.Seedlings form a rosette of waxy leaves with variable, lobed leaf margins. Wild lettuce leaves are similar to sowthistle leaves but lack prickles on leaf margins. Depending on the species, plants can mature to 1 to 4 feet in height. In warm weather, plants can bolt and some species may reach 8 feet in height. Some species produce insignificant flowers that are pale yellow and form on branched heads. The seed head is similar to a dandelion but smaller.',
        '["Asteraceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Weed"]'
    ),
    (
        'Spinach',
        'spinach.jpg',
        2.0,
        5,
        7.0,
        55,
        'Spinach is an annual vegetable in the Amaranth family that is widely grown for use as a leafy green in salads and cooked dishes.  It can be grown at home in containers or beds and tolerates areas too shady for most other vegetables to thrive.Spinach grows best in moist, rich, well-drained soil in full sun to light shade– it can tolerate 3-4 hrs of sun a day, and some shade can be beneficial in hot weather.  Plant seeds 1/4-1/2 inches deep and thin to 2-3 inches apart.  For spring crops, plant seed directly in the soil in early spring or start indoors 8 weeks before first frost for later transplant.  For fall crops, plants can be started indoors early or direct seeded after the hottest heat of summer has passed.  For an extended harvest, plant seeds every one to two weeks.  Plants are somewhat frost tolerant and can survive temperatures up to 20F.  Spinach can be grown in containers as small as 1 gal. and as shallow as 4-6 in.Harvest leaves at any size.  Spinach plants will continue to grow new leaves after harvesting, especially when harvested small, allowing for continuous harvests throughout the season.  Spinach grows best in the cool weather of spring and fall.  It is sensitive to the increasing day length and heat that comes with summer, causing plants to "bolt" and send up flowering stalks; as this process stops leaf growth and makes them bitter, bolt-resistant cultivars are recommended if growing a spring crop in warm climates.',
        '["Amaranthaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Rapid"]'
    ),
    (
        'Pepper',
        'pepper.jpg',
        1.5,
        6,
        6.0,
        75,
        'The genus of peppers, composed of species native across Central and South America, is in the Solanaceae (nightshade) family, which is the same as many other food plants such as tomatoes, eggplant, and potatoes. Many cultivars of these species are grown as food, spice, and medicine. Peppers prefer full sun but grow well in any soil as long as it drains well. Although each species and cultivar differs in size and shape, the most iconic part of these plants is the fruit, most often bright red, hollow, and intensely spicy. This "heat" is due to the presence of capsaicin in the flesh and seeds, a trait that has been altered through breeding for various purposes. Some cultivars are sweet with no spice, and others have world record-breaking quantities of capsaicin within. Peppers tend to be tolerant to both drought and heat and resistant to damage from deer.Among commonly cultivated species, the plants tend to be small enough to lend themselves toward container gardening. Some cultivars have ornamental value and can be planted as part of a decorative arrangement, but they are most commonly found growing in vegetable gardens.  ',
        '["Solanaceae", "Annual", "Edible", "Vegetable", "Low-Maintenance", "Rapid"]'
    ),
    (
        'Mint',
        'mint.jpg',
        2.0,
        4,
        6.0,
        60,
        'Spearmint is a flowering, aromatic herb or groundcover in the Lamiaceae (mint) family native to Europe.   In its natural haibtat it is found growing in moist fields and pond or lake margins. It can be distinguished from other mints by its almost hairless (glabrous) leaves that are attached to the stem with a very to almost non-existant petiole (sessile). The small lilac, pink, or white flowers appear in terminal spikes in late summer and can be sheared after bloom to remove flower spikes and stimulate new vegetative growth. Leaves have a strong spearmint fragrance and taste, and may be used to flavor teas, in salads, as a garnish or in pot pourris. The genus name comes from Minthe or Menthe, a water nymph in Greek mythology, who was transformed by Persephone into a mint plant in revenge for Minthe''s ongoing affair with Hades (husband of Persephone). The species name means spike.This upright perennial thrives in full sun in organically rich, well-drained, moist soils growing quickly 1 to 2 feet high and wide with bright green leaves and shoots. It does tolerate partial shade and a wide range of soil types, but does not do well in dry soils. The square stems can root wherever they touch the ground and it also spreads by rhizomes. Soil barriers can restrain rhizomatous spread if plants are grown in borders or other areas where spread is unwanted.It is widely used for culinary purposes, and is known as one of the best mints for flavor. Use the flowers and leaves fresh or dried in teas, beverages, jellies, syrups, candies, ice creams, lamb dishes, and mint sauce.',
        '["Lamiaceae", "Perennial", "Edible", "Herb", "Medium-Maintenance", "Spreading"]'
    ),
    (
        'Rosemary',
        'rosemary.jpg        ',
        1.0,
        6,
        6.5,
        65,
        'Rosemary is an aromatic, perennial, evergreen shrub in the Lamiaceae or mint family that is valued for its fragrant, ornamental foliage, and as an enhancement in cooking. The shrub grows from 4 to 5 feet tall and is generally erect and rounded. The aromatic, needle-like leaves are green on the upper surface, and the undersides are white and tomentose. The flowers are tiny, blue, lavender, or white, and are two-lipped and whorled around the square stems. It is frequently cultivated as an ornamental, as a culinary herb, or for use in sachets or potpourris.It is native to Africa, Europe, Western Asia, and the Mediterranean and is found in dry, rocky areas.The genus name, Salvia, is derived from the Latin word salvo which means "to save or heal." This refers to the medical uses of some plants in this genus. The epithet, Rosmarinus, comes from the Latin words ros meaning "dew," marinus meaning "sea," or in other words, "dew of the sea. " This is most likely a reference to the ability of this plant to thrive well in coastal areas, sea cliffs, and exposure to ocean mists.Rosemary does best in light, slightly acidic, dry to medium, well-drained soils in full sun. It tolerates drought, partial shade, salt, heavy pruning, and most soil types except clay. It is easily transplanted and rooted. However, it has a low tolerance for wet, humid environments and requires careful tending in an appropriate spot. Once the bloom has passed, severely pruning is an option to encourage dense foliage growth. Rosemary plants are slow to germinate from seed, and gardeners might find more success propagating from stem cuttings, layering, or division.',
        '["Lamiaceae", "Perennial", "Edible", "Herb", "Medium-Maintenance", "Irregular"]'
    ),
    (
        'Peas',
        'peas.jpg',
        1.5,
        5,
        6.5,
        55,
        'Peas are annual, cool-season vegetables in the bean family (Fabaceae), native to Eurasia and most often grown for their edible seeds or seed pods. There are many cultivars and varieties. Peas grow best in full sun and moist, well-drained soil. They can tolerate a range of soil textures so long as there is good drainage and a pH range of six to eight. While they can tolerate partial shade, they need full sun to properly develop flowers and set fruit. Peas stop growing at temperatures above 85 degrees F. In many parts of North Carolina, this leaves a very small growing window. Plant seeds directly in the soil as soon as the ground has thawed; young plants have some frost resistance. Handle seeds gently as they damage easily and will be less likely to germinate. Seeds should be planted 1 inch deep and 2 to 3 inches apart. Peas can also be grown in containers of a minimum size of two gallons and a depth of 12 inches. The plants often reach the harvest stage in 60 days. Plantings can be staged a week apart for a longer harvest season.Peas come in tall, vining varieties that grow peas throughout the season and shorter bush varieties that set a determinate crop all at once. Vining varieties are best grown on a trellis such as stakes and twine or a metal fence in order to minimize disease. Other varieties differ in seed and pod shape. Garden peas grow round, starchy seeds and fibrous pods. Snow pea pods are harvested with barely-grown seeds, and sugar snap peas have juicy green-bean like pods and almost-full seeds.',
        '["Fabaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Climbing"]'
    ),
    (
        'Tulip',
        'tulip.jpg',
        1.0,
        6,
        6.0,
        50,
        'The common tulip is a bulbous perennial herb in the lily family (Liliaceae) that is native from southern Europe to central Asia. Tulips grow from 4 to 28 inches in height and bloom in middle to late spring with flowers that come in all colors except true blue. Plant tulips three times the depth of the bulb in fertile, organically rich but well-drained, medium-moisture soil in full sun. Bulb and root rots may occur in wet, poorly drained soils. They grow best in areas with cool, moist winters and warm dry summers and are typically grown in mass plantings. The plant is intolerant of heat and loses floral vigor when soil temperatures reach 70 degrees F. Tulips may be grown as perennials or as annuals, although species tulips often perform better than hybrid plants as perennials. When growing tulips as perennials, promptly remove spent flower stems after bloom to prevent seeding, but do not remove foliage until it yellows. In most cases, tulip performance declines substantially starting with the second year. Many gardeners and horticulturists treat tulips, particularly hybrids, as annuals.Tulips make wonderful outdoor container plants, and they can be forced in containers for indoor displays. They are often grown in borders and cutting gardens, but their maximum impact is made in mass plantings when in bloom.',
        '["Liliaceae", "Perennial", "Ornamental", "Flower", "Low-Maintenance", "Rapid"]'
    ),
    (
        'Sunflower',
        'sunflower.jpg',
        1.5,
        6,
        6.5,
        70,
        'There are 150 species of sunflower, most of which are native to North America.  They are annuals or perennials in the Asteraceae (daisy) family and have rough sandpapery leaves and showy daisy-like flowers that come in a variety of colors. All species are tall and many can become weedy as they self-seed easily but their cheery summer and fall flowers make up for any inconvenience.Although generally preferring moist soil, some species will tolerate poor drainage.  Plant in the full sun for the most blooms and enjoy the flowers from late summer until the first frost.  Leave the seed heads standing to provide a late fall and winter food source for birds.The giant sunflower H. annuus is the plant that provides the seed we snack on and sunflower oil.  Jerusalem artichokes, or H. tuberosus, have tasty starchy edible tubers',
        '["Asteraceae", "Annual", "Ornamental", "Flower", "Low-Maintenance", "Clumping"]'
    ),
    (
        'Marigold',
        'marigold.jpg',
        1.5,
        6,
        7.0,
        70,
        'Tagetes, or marigolds, is a genus in the sunflower or aster family that includes 49 species of flowering, herbaceous plants with a shrubby form that is native to Central and South America and have been introduced throughout the world. Depending on their environment and whether they are grown as an outdoor or indoor plant, Marigolds can be annuals or perennials.The plants give off a strong aroma when crushed and marigold flowers are bitter with a spicy, herbal flavor. The ''Lemon Gem'' and ''Tangerine Gem'' cultivars, however, are quite flavorful. The flowers can be made more palatable if you remove the bitter, white base of the petal. The plant is often used in tea, to color foods, and as a substitute for tarragon; however, it can be harmful if eaten in large amounts. The juice, sap, or thorns of these plants may cause a painful skin rash or irritation. Wash the affected area of the skin with soap and water as soon as possible after contact.The name Tagetes comes from the name of an Etruscan seer supposedly born from the plowing of the earth and refers to the ease with which plants of this genus come out each year either by the seeds produced in the previous year or by the stems which regrow from the stump already in place. The common name, marigold, is a shortened form of "Mary''s gold."',
        '["Asteraceae", "Perennial", "Ornamental", "Flower", "Low-Maintenance", "Clumping"]'
    ),
    (
        'Peony',
        'peony.jpg',
        1.5,
        6,
        6.0,
        75,
        'Peonies are woody,semi-woody or herbaceous perennials in the peony family (Paeoniaceae) often planted for their very large, showy flowers. Some cultivars are fragrant. Most species originate in Asia, but some species are found in Europe and around the Mediterranean Basin. Two species (not in cultivation) are native to western North America. Paeonia is the classical Greek name for peony.Peonies do well in full sun to light shade and prefer deep, fertile soils that are well-drained.  Locate them in an area that gets good air circulation, not up against a home or a wall. They like some afternoon shade and will require quite a bit of water in the early part of the growing season to establish their leaves and flower buds. They can take quite a while to establish and often will not produce flowers for the first year or two after transplanting. Once established, however, plants can live for decades. Each plant will bloom for about 7–10 days in the late spring to early summer so planting a variety of peonies with staggered bloom time will help extend the season. They can be divided in the fall and spread around the landscape. Plants may require support for large, double flowers especially if they become wet with rain. The foliage remains attractive through the summer until fall. Peonies grow well in the mountains and cooler Piedmont but languish in warm areas where their chilling requirement is difficult to meet. They do best in zones 5–7 but can grow in zones 3–8. If you are in a warm area, plant low-chill types, do not plant the crowns more than one inch deep, and do not apply mulch in the winter, as it can act like an insulating blanket. Overly shaded sites can inhibit flowering. This plant is outcompeted by tree roots when planted close to trees.',
        '["Paeoniaceae", "Perennial", "Ornamental", "Flower", "Medium-Maintenance", "Clumping"]'
    ),
    (
        'Azalea',
        'azalea.jpg',
        2.5,
        3,
        6.0,
        60,
        'Azaleas and rhododendrons are woody, evergreen or deciduous, rounded shrubs in the Ericaceae (blueberry) family. They are native to the United States and Asia and there are many cultivars and varieties, some native to North Carolina. They typically grow 6 to 10 feet tall and 5 to 8 feet wide. The genus name derives from the Greek words rhodo, which means rose, and dendron, meaning tree.These plants prefer moist, well-drained, acidic soils in dappled shade and protection from afternoon sun which can scorch the leaves. They do not tolerate dense clay, so if you have clay soil, amend with organic material. The roots may rot if soil does not drain well. Plant the root ball high in the soil to help with drainage issues. Avoid overwatering and over-fertilizing. Pruning, if desired, may be done after flowering. Azaleas and rhododendrons are at home as understory shrubs planted in groups in woodland or naturalized areas, or as specimens in pollinator gardens where the flowers will attract hummingbirds and the specialized bee Andrena cornelli. Some varieties are grown as houseplants.',
        '["Ericaceae", "Woody", "Ornamental", "Flower", "Medium-Maintenance", "Clumping"]'
    ),
    (
        'Lilac',
        'lilac.jpg',
        1.5,
        6,
        7.0,
        60,
        'Early lilac is a perennial shrub or tree in the olive family (Oleaceae). It is native to China. The species epithet, Latin for “oblate,” highlights the fact that the leaves are wider than they are long.It is hardy, preferring hot summers and cold winters. Good air circulation is needed to prevent diseases. Early lilac grows best in moist, fertile, well-drained soils where the pH hovers between slightly acidic and slightly alkaline. Removing the spent blooms before they set seed will give you more blooms the next year.This is the earliest-blooming lilac, but consequently, flower buds are susceptible to frost injury in early spring. This is the only lilac that gives any appreciable autumn color. This is best planted near a patio or walkway where the fragrance can be enjoyed.',
        '["Oleaceae", "Perennial", "Ornamental", "Shrub", "Low-Maintenance", "Spreading"]'
    ),
    (
        'Corn',
        'corn.png',
        1.3,
        6,
        6.5,
        80,
        'Grows like sweet corn.  Corn is a warm weather crop and should not be planted until the soil warms up to 60° F. It is one of the taller home garden crops, so locate it where it will not shade out other crops. Plant in full sun, in fertile, well-drained soil. Several rules apply to insure an adequate corn crop:Corn is wind pollinated, and to insure adequate pollination, sow seeds in several rows to form a square, or on hills with several plants in a circle. A minimum of 12 or more plants is usually necessary. Do not plant in one long row.Corn is a heavy feeder and must have ample nitrogen and water at all times, but water the soil, not the plant or pollination could suffer.Corn roots do not tolerate disturbance well, so when thinning corn, cut the excess sprouts instead of pulling them. Do the same with nearby weeds and after corn is established mulch to reduce weeds rather than cultivating around their roots and damaging them.Cross-pollination from other corn varieties can adversely affect some sweet corns, so follow cultivar label directions precisely to avoid pollen contamination from other corn. 5. Time of harvest is important for some sweet corns, so follow harvest directions carefully for the particular variety you are growing. Hard corns need to dry on the stalk, so harvest time is not a particular issue for them.',
        '["Poaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Rapid"]'
    ),
    (
        'Radish',
        'radish.png',
        1.0,
        6,
        7.0,
        55,
        'Radishes have been in cultivation for thousands of years and are grown all over the world. The fleshy taproots range from 1 inch to 3 feet long depending on the cultivar and come in colors including white, pink, red, purple and black.  They are fast growing vegetables, ready to harvest in 3-6 weeks, making them great for use in a children''s garden.  The edible white or pink flowers have a spicy flavor and are often used in salads.  The leafy tops can also be eaten and are best cooked to improve the texture.  While most commonly grown for food, they are also grown for livestock forage and as a cover crop for breaking up compacted soil.Radishes grow best in full sun to part shade and a well-drained loamy or sandy soil.  While they can grow in partial shade, at least 4 to 5 hours a day, it will take longer for the root to grow to a harvestable size.  Lighter, looser soils will yield a smoother, rounder, and more tender root.  Light soils need to be watered more frequently and consistent moisture is needed to produce a good flavor.  Roots will turn woody with age, hot weather, and if the plant bolts, although if this happens the flowers can be harvested and used instead.Radishes are a cool-season crop and grow best in spring and fall.  In NC, plant seeds sometime in mid-February to early April for a spring crop and from August to mid-September for a fall crop.  Plant the seeds of smaller cultivars 1/4 to 1/2 in deep and larger cultivars up to 1 in deep.  Thin small varieties to 1-3 in apart and large varieties 4-6 in.  Longer varieties need deep soil that raised beds readily provide, at least 2-3 feet deep; smaller varieties can easily be grown in containers at least 2 quarts in size and 4-6 in deep.  Plant new seeds every 2 weeks to extend the harvest.Radishes are ready to harvest in as little as 3-6 weeks, whenever they reach a useable size.  They are ready when you can see the tops start to peak through the soil.  Small varieties can be pulled by hand; for large varieties, use a spade or fork to help pull the root from the soil.  Small roots last 1-2 weeks in the fridge while large ones like Daikon can last up to 2 months.',
        '["Brassicaceae", "Biennial", "Edible", "Vegetable", "Medium-Maintenance", "Rapid"]'
    ),
    (
        'Cabbage',
        'cabbage.jpg',
        1.5,
        6,
        7.5,
        60,
        'The Capitata Group of Brassica oleracea is cabbages. The genus name Brassica is Latin for cabbage.  This group has hearty leaf plants and grows best at cooler temperatures, typically around 60 degrees.  Temperatures higher than 75 degrees can induce bolting, when your plants grow too quickly, then stop flowering and set seeds.  The best growing conditions include full sun, shade can slow the growing process.There are three types of cabbages.  Common cabbage has dark green leaves.  Dutch cabbage has a larger heart and leaves and a milder flavor and is pale green or even white. Red cabbage has purplish colored leaves.  They are in flower from May to August and ready for harvest from July to September.A head of cabbage can weigh between 1 to 9 lbs.A versatile plant, it can be pickled, fermented, steamed, stewed, braised, sauteed, or eaten raw.  The shredded leaves can be used in salads.  Dutch cabbage is the more tender and sweeter variety, most suitable for eating raw.  Red cabbage is used for pickling.They have a large terminal bud that is edible.  Savoy cabbage has puckered leaves that can be shredded to make coleslaw.  ',
        '["Brassicaceae", "Annual", "Edible", "Vegetable", "Low-Maintenance", "Clumping"]'
    ),
    (
        'Blueberry',
        'blueberry.jpg',
        1.0,
        2,
        6.0,
        75,
        'Low bush blueberry is a low-growing small native deciduous shrub.  It can be found growing in open conifer woods, sandy or rocky balds and old fields. Prefers full sun to partial shade, acidic moist to dry soils.  Plant more than one for the best fruit production.  It is commonly propagated in the spring by taking softwood cuttings or you can grow it from seed. There are two types of blueberries: highbush and low bush. Highbush are those that are commonly found in stores. Lowbush blueberries are smaller and sweeter, and are therefore used often in jams and jellies.This plant will benefit from acidic soils that are moist, high in organic matter and well drained.  It can be grown in full sun to part shade, however, a location with full sun with result into more blooms, more fruit and a more showy fall foliage.Blooming occurs on old wood.  ',
        '["Ericaceae", "Perennial", "Edible", "Fruit", "Low-Maintenance", "Multi-stemmed"]'
    ),
    (
        'Blackberry',
        'blackberry.jpg',
        1.5,
        6,
        7.0,
        70,
        'Himalayan blackberry is a European species of perennial deciduous shrub in the rose (Rosaceae) family now widespread in North America. It is common in the mountains of North Carolina and occasionally found on the Piedmont and coastal parts of the state.This plant is easy to propagate with rooting canes (branches) than seeds. It grows well in full sun or light shade and in most soils (sandy, loamy, or clay). It prefers well-drained loamy soil. The fruit is edible, but not as useful for that purpose as other species of blackberry.This blackberry has biennial stems, that is, it produces a number of new stems each year from the perennial rootstock that fruit in their second year and then die. The plant produces apomictic flowers, which produce fruit and viable seed without fertilization, each seedling is a genetic copy of the parent.',
        '["Rosaceae", "Perennial", "Edible", "Fruit", "High-Maintenance", "Rapid"]'
    ),
    (
        'Fig',
        'fig.jpg',
        1.3,
        6,
        6.0,
        75,
        'Common fig is a woody, deciduous, multi-stemmed, spreading tree or shrub in the mulberry family (Moraceae). It is native to the Mediterranean to Central Asia and quickly grows to a mature size of 10 to 30 feet tall and wide with a rounded habit. The genus name Ficus means edible fig, and the species epithet carica refers to Caria, a region in southwestern Turkey known for growing figs.Plant common fig in full sun to partial shade in organically rich, well-drained, moist soil that is neutral to acidic; it does not tolerate alkaline soils. Light pruning each winter may be necessary to maintain an attractive shape. The fruits form on new wood. Mulch roots to maintain moisture and especially in the fall to protect the plant through the winter. Propagate by layering or stem cutting. It produces many suckers, which can form thickets, and cause the plant to become weedy. The fruits come in various colors and ripen in late summer or fall. The flowers form inside a cavity inside the fruit and, in North America, the fruit forms without any pollination. The fig fruit is highly edible when consumed fresh, cooked, used in preserves, or dried. Birds and other wildlife also enjoy figs. Plant the common fig tree in an edible garden and consider placing it against a south wall to take advantage of radiant heat, or in other protected areas of the landscape especially in zone 7. It grows well in containers, but containers must be overwintered indoors.',
        '["Moraceae", "Perennial", "Edible", "Fruit", "Medium-Maintenance", "Rapid"]'
    ),
    (
        'Thyme',
        'thyme.jpg',
        0.5,
        6,
        7.0,
        70,
        'The genus, Thymus, is a member of the Lamiaceae or Mint family and has about 350 different species of perennial herbaceous plants and evergreen shrubs. The species has various sizes and growth habits. Thyme has been cultivated for centuries as an ornamental or for culinary use. They are native to Greenland, the temperate and subtropical areas of Euroasia, and Northeast Tropical Africa.Common Thyme (Thymus vulgaris) is often used in cooking to flavor soups, stews, sauces, and meats. Different species have a variety of flavors and fragrances that include caraway, lemon, nutmeg, orange, and oregano. Some species, such as Creeping Thyme (Thymus serpyllum), are used primarily as groundcovers. Other species, such as Wooly Thyme (Thymus praecox), may be used as lawn substitutes. The essential oils of the thyme leaves have been used to make perfumes, antiseptics, expectorants, and deodorants.The origin of the word, "thyme," is from the Greek word, thumos, which means "courage." During Medieval times thyme was thought to be an emblem of bravery, strength, and courage. The word thyme may also have been derived from the Greek word, thymos, meaning "perfume."Thyme grows best in full sun and dry, sandy, or rocky soils. They can tolerate very alkaline soils. They prefer well-drained soils and can tolerate drought once they are established. They are intolerant to wet soils or poor drainage. The plant is low maintenance, but it should be trimmed when it gets leggy. When using thyme for culinary purposes, it is best to harvest the leaves just before flowering when the essential oils are at their peak.The common method of propagation is by stem cuttings, division, and seeds. Due to erratic germination, some species of thyme are difficult to propagate from seeds.The stems of the thyme plants are thin, wiry, and woody. The leaves are tiny, fragrant, and their colors vary from green to silver, depending on the species. The flowers are tiny, tubular, and colors vary from white, pink, to purple. The fruits are tiny schizocarps.The flowers of thyme are rich in nectar and attractive to bees and butterflies. Thyme is an excellent plant for pollinator gardens, rock gardens, or herb gardens. Some species are primarily ornamental and due to their creeping habit may be used between stepping stones, rocks, ledges, or walls. They may also be used as a border plant. Thyme is typically deer and rabbit resistant.',
        '["Lamiaceae", "Perennial", "Edible", "Herb", "Low-Maintenance", "Dense"]'
    ),
    (
        'Sage',
        'sage.jpg',
        1.0,
        4,
        7.0,
        65,
        'Sage is a genus in the Lamiaceae (mint) family and is found all over the world. There are many species and cultivars and lots of variation in their leaf shape and texture, but it is easy to tell they are in the mint family because of their square stems. Most members of this genus are small upright shrubs reaching 1 to 3 feet tall and wide. The name Salvia is derived from the Latin term salveo, which means ‘be well’ and refers to the plant''s medicinal properties.Sages need to be planted in full sun to partial shade and in well-drained, highly organic soil. They are drought and salt tolerant and resistant to deer. Propagate by division, seed, or stem cutting. The flowers provide excellent late season color, so sages are a good companion plant in a native, butterfly, pollinator, or drought-tolerant garden. Edible species are also excellent in an herb garden.',
        '["Lamiaceae", "Annual", "Edible", "Herb", "Low-Maintenance", "Wildflower"]'
    ),
    (
        'Dill',
        'dill.jpg',
        1.0,
        4,
        6.0,
        65,
        'Anethum graveolens, or Dill, is an aromatic self-seeding annual herb. The genus name, Anethum, comes from the Greek meaning to calm or soothe while the species name, graveolens, means emitting a heavy odor or strong smelling. Dill is believed to have originated in the Mediterranean and has a long history of use as a culinary and medicinal herb and was believed to aid digestion.For the most productive yield and strongest stems, dill grows best in temperate climates with full sun in well-drained, slightly acidic soil. Plant dill seeds in early spring, a week or two before the last hard frost date, about ¼ inches deep as they need light to germinate. Plant every 2 or 4 weeks to keep it ready for fresh use. Seedlings germinate in about 10 to 14 days. Because of its long taproot, dill is a poor candidate for transplant. Dill plants can survive low temperatures but grow best in temperatures of about 70 degrees. Consistent watering is best and prevents the plant from  bolting; however, plants that get too much water or extra shade can be lanky and flop over requiring support and the plants should be protected from strong winds. The dill seed is harvested after the stems begin drying out; the seeds turn golden brown in color, and the seed clusters gain weight. Dill resembles fennel and can be distinguished by its smell and hollow stems.',
        '["Apiaceae", "Annual", "Edible", "Herb", "Low-Maintenance", "Ascending"]'
    ),
    (
        'Squash',
        'squash.jpg',
        1.0,
        6,
        7.0,
        70,
        'Cucurbita is a genus of annual, warm-season, vining plants in the cucumber family (Cucurbitaceae) native to North and South America. It includes commonly cultivated vegetables (although botanical terms, they are fruit) such as summer and winter squashes, pumpkins, zucchini, and ornamental gourds. Their size varies with the cultivar, from 1 to 5 feet tall and 2 to 25 feet wide or long.These plants require full sun. Being an annual crop, they will also require regular irrigation and moist, well-drained, organically rich soil. Give them sufficient space to provide good air circulation.Plant them in small groups or mass plantings and site them in vertical spaces or in edible or children’s gardens.',
        '["Cucurbitaceae", "Annual", "Edible", "Vegetable", "High-Maintenance", "Creeping"]'
    ),
    (
        'Eggplant',
        'eggplant.jpg',
        1.0,
        6,
        5.5,
        80,
        'Eggplant is an annual or short-lived perennial plant that is very sensitive to cold temperatures. It grows fastest when the temperature ranges between 70 and 85 degrees. It produces an edible shiny glossy fruit. The plant may grow 2 to 4 feet tall and is multi-branched. The leaves and stems have star-shaped hairs, and the small violet flowers are also star-shaped. Eggplant or Aubergine is a member of the Solanaceae or nightshade family which also includes tomatoes, potatoes, and peppers.  It is grown primarily as a food crop.This species is native to South Central China, Laos, Myanmar, Thailand, and Vietnam. The plant is grown as a perennial in South Asia. It is now cultivated worldwide. In North Carolina, eggplant is considered an annual. The genus name, Solanum, is from the Latin word solamen, which means "comforting or soothing." The species name, melongena, references the fruits melon shape. Another source states that the species name, melongena, has origins from the Italian name "melanzane," which is derived from "mela insane" or "mad apple."The eggplant grows best in full sun. It prefers moist, well-drained, fertile, sandy, and loamy soils with a pH range of 5.5 to 6.8. It is propagated by seeds and germination occurs in 8 -12 days. The fruits may be harvested in about 105-133 days. The plant''s flowers attract bumblebees.The leaves and stems are covered with star-shaped hairs and sometimes prickles. The flowers are solitary, star-shaped, and usually violet in color. The fruit is a large fleshy smooth berry. The fruit color varies from white, green, or purple to black depending on the cultivar. The fruit has many pale brown kidney-shaped seeds. If you consider growing eggplant in your vegetable garden, caution should be taken to protect children and pets.',
        '["Solanaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Multi-stemmed"]'
    ),
    (
        'Broccoli',
        'broccoli.png',
        1.3,
        4,
        6.5,
        55,
        'Ornamental cabbage is the wild ancestor of a group of annual cool weather vegetable plants including kale, collards, broccoli, cauliflower, and kohlrabi.  These crops are referred to as Cole Crops.  Ornamental cabbage is in the Brassicaceae (mustard) family. The genus name Brassica is Latin for cabbage, while oleracea means vegetable/herb. These plants are grown for their edible leaves. In its native habitat, it can be found growing along coastlines on rocky sea cliffs in Western Europe.  It can grow in a wide range of conditions, however, and will perform at its best when located in full sun in nitrogen-rich, alkaline soil with good drainage. After flowering, cut out the flowering stems when the flowers show signs of forming seed pods. That will conserve the plant’s energy or resources for additional leafing up. Propagate by seed or stem cuttings. The foliage of ornamental cabbage is fleshier and thicker than other Brassica species. That gives it an edge in difficult growing conditions, allowing the foliage to store water and nutrients. It forms a loose head of large green or blue-green leaves that are edible.  They can be boiled or steamed until tender. Ornamental cabbage will grow in a container and is as at home in a meadow or pollinator garden as it is in an edible garden. It can be used in a border or a mass planting. ',
        '["Brassicaceae", "Biennial", "Edible", "Vegetable", "Medium-Maintenance", "Erect"]'
    ),
    (
        'Cauliflower',
        'cauliflower.jpg',
        1.3,
        6,
        7.0,
        60,
        'The Botrytis Group of Brassica oleracea is most commonly called cauliflower.  The genus name Brassica is Latin for cabbage.  It is a cool-season vegetable that does not tolerate heat well, therefore, it is typically grown in the spring or fall.  Sow seed in late spring for a summer harvest, then again in late summer for fall harvesting.  It is grown for the edible stem, buds, and flowers. The unshowy flowers have a spicy flavor. For best-growing results, keep the soil moist and plant in a loam-based soil that is rich in nitrogen.  The use of compost is ideal for soil enrichment.  Mulching around the plants will help protect the surface roots and retain moisture.  It is not a frost-tolerant plant.  It should not be sown if there is any possibility of frost.  Plants are ready for harvesting when the heads are 6-8" across, firm and tight. Cauliflower is now available in a variety of colors.In the form of compact heads, these are a popular vegetable that can be served raw or boiled.  Often they are accompanied by a white sauce.They are also used in pickle production.',
        '["Brassicaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Erect"]'
    ),
    (
        'Onion',
        'onion.jpg',
        1.0,
        6,
        8.0,
        75,
        'Shallots are members of the onion family native to Asia.  They have a flavor described as somewhere between onion and garlic.  It is resistant to damage by deer and rabbits and can be planted near black walnut trees. The bulb will make several offsets during the growing season. The tops can also be used like chives but harvesting these will delay the bulb formation. The creamy bulbs are 2-3 inches long by 3-4 inches wide and depressed oval in shape. The outer covering is tinged with red, purple or brown. Plant bulbs in moist but well-drained fertile loose soils in full sun as soon as the ground can be worked in spring about 1/2 to 1 inch deep and 6 inches apart. The bulbs are ready to harvest when at least 2/3 of the tops have died down. Dig shallots with a garden fork to prevent damage and allow to dry or "cure" for 2-3 weeks before using. Store in mesh bags or crates for good air circulation.',
        '["Amaryllidaceae", "Bulb", "Edible", "Vegetable", "Medium-Maintenance", "Arching"]'
    ),
    (
        'Potato',
        'potato.jpg',
        2.0,
        6,
        5.5,
        65,
        'Potatoes are herbaceous perennials in the nightshade family (Solanaceae), but they are grown as annual crops. Potatoes are native to South America in parts of Argentina, Bolivia, Chile and Peru. They are now widely cultivated and major producers include China, Germany, India, Russia and the United States. The genus name, Solanum, is derived from the Latin word, solamen, which means "comforting or soothing." The species name, tuberosum, means "tuber."Potatoes grow best in full sun and well-drained, sandy and acidic soil. Poorly drained soil may cause tubers to rot, and acidic soil helps to prevent bacterial scabs. Light soil, if consistently moist, can help the plant grow large, evenly shaped potatoes. Raised beds provide good drainage and containers or grow bags can be suitable for growth as long as they are at least 2 feet deep and hold at least 30 gallons. Potatoes also may be grown in trenches to make the process of hilling easier. Potatoes are most often grown from "seed potatoes," which are small tubers or pieces of tubers that sprout into a new plant. Buying certified disease-free seeds can help prevent problems such as potato late blight. Potatoes from the grocery store are often treated with sprout inhibitors and therefore may not be reliable for planting. Before planting, cut seed potatoes so each piece has at least two eyes and allow it to rest outside for a day to let the cut end scab over. Plant seed pieces 5 to 6 inches apart with the eyes facing up. As they grow, pile soil or mulch up around the base of the plant. This encourages the growth of more tubers along with the submerged parts of the stem. Do this once the plants are one foot tall and once or twice more throughout the season. Tubers will turn green and produce toxic compounds if not sufficiently covered. In North Carolina try to have potatoes planted sometime between mid-February and the end of March; they can tolerate a bit of frost. Potatoes can be harvested mature when the tubers are fully grown or the plant has dried up around June. They may also be harvested early as "new" potatoes once the plants begin to flower. These young potatoes still have thin, delicate skins and are considered a delicacy. New potatoes can be harvested about 7 to 8 weeks after planting. Mature potatoes can take 3 to 4 months before they are ready for harvest. Proper crop rotation, clean garden tools and using disease-resistant cultivars will reduce pests and diseases which ultimately improves crop yields. ',
        '["Solanaceae", "Annual", "Edible", "Vegetable", "Medium-Maintenance", "Spreading"]'
    );
INSERT INTO `plantpal`.`Users` (
        `first_name`,
        `last_name`,
        `username`,
        `hash`,
        `salt`
    )
VALUES (
        'Michael',
        'Richardson',
        'maricha6',
        '59b881b55f0a73c2e3c9a546ab452a1a68e030cf6920c0063a3977bcd94473cc8a3f375043677b929fd0f14a7b35c49a751bfaa29d8dd63281f3c5d324563229',
        'e57b87f4807c0f1a18c90707faffb548'
    ),
    (
        'Jacob',
        'Friend',
        'jsfriend',
        'd2680670bf81869d8fbc5e52b1aee0d9e1f7def483ecfab4dfaa67e5d48860cdac43e174788518ee47aec7424da9b28a7c5777ecf62b9c3c8da4a160655d7fa7',
        '46f68be855f4e7a74ca89f0331d57fd1'
    ),
    (
        'Lalitha',
        'Edupuganti',
        'ledupug',
        '7bdf1f773e5efe8e6346bb662a6867b97484bb9b0c077b4b8890cef91bcce43155a051c5515933503e49e5f2425e034797100f0934507ba0aa609c779dc83ec5',
        '9fc367ca7b70d25a5b4f87f42709633f'
    ),
    (
        "Stu",
        "Dent",
        "student",
        "058e8b2fbee5f129d5bc763f7410db7e699654f95460e33b38fbe6bdf9acd1eb28b80a704bf0508d86221a899ada1e31b1e96aed895cdce5a24048593790593c",
        "e818e2afce0807d320d0cfd9a61799d6"
    );
INSERT INTO `plantpal`.`Plants` (`user_id`, `profile_id`, `created_at`)
VALUES (1, 1, '2024-08-30 08:00:00'),
    (1, 2, '2024-09-03 08:00:00'),
    (1, 3, '2024-09-05 08:00:00'),
    (1, 4, '2024-09-14 08:00:00'),
    (1, 5, '2024-09-30 08:00:00'),
    (1, 6, '2024-10-04 08:00:00'),
    (1, 7, '2024-10-10 08:00:00'),
    (1, 8, '2024-09-09 08:00:00'),
    (1, 9, '2024-08-30 08:00:00'),
    (1, 10, '2024-08-30 08:00:00'),
    (1, 11, '2024-08-30 08:00:00'),
    (1, 12, '2024-08-30 08:00:00'),
    (1, 13, '2024-08-30 08:00:00'),
    (1, 14, '2024-08-30 08:00:00'),
    (1, 15, '2024-08-30 08:00:00'),
    (2, 5, '2024-08-30 08:00:00'),
    (2, 13, '2024-08-30 08:00:00'),
    (2, 15, '2024-08-30 08:00:00'),
    (3, 3, '2024-08-30 08:00:00'),
    (3, 4, '2024-08-30 08:00:00'),
    (1, 2, '2024-09-28 10:50:20'),
    (4, 2, '2024-09-28 10:50:20'),
    (4, 4, '2024-09-28 10:50:20'),
    (4, 6, '2024-09-28 10:50:20'),
    (4, 8, '2024-09-28 10:50:20'),
    (4, 10, '2024-09-28 10:50:20'),
    (4, 12, '2024-09-28 10:50:20'),
    (4, 14, '2024-09-28 10:50:20'),
    (4, 16, '2024-09-28 10:50:20'),
    (4, 18, '2024-10-28 10:50:20'),
    (4, 19, '2024-10-28 10:50:20'),
    (4, 20, '2024-10-28 10:50:20'),
    (4, 21, '2024-10-28 10:50:20'),
    (4, 22, '2024-10-28 10:50:20'),
    (4, 23, '2024-10-28 10:50:20'),
    (4, 24, '2024-10-28 10:50:20'),
    (4, 25, '2024-08-28 10:50:20'),
    (4, 26, '2024-08-28 10:50:20'),
    (4, 27, '2024-08-28 10:50:20'),
    (4, 28, '2024-07-28 10:50:20'),
    (4, 29, '2024-07-28 10:50:20'),
    (4, 30, '2024-07-28 10:50:20'),
    (4, 31, '2024-07-28 10:50:20');
INSERT INTO HeightMeasurements (plant_id, value, time)
VALUES (1, 0.50, '2024-09-01 08:00:00'),
    (1, 0.75, '2024-09-02 08:30:00'),
    (1, 1.00, '2024-09-03 09:00:00'),
    (1, 1.20, '2024-09-04 09:15:00'),
    (1, 1.45, '2024-09-05 09:45:00'),
    (1, 1.70, '2024-09-06 10:00:00'),
    (1, 1.90, '2024-09-07 10:30:00'),
    (1, 2.15, '2024-09-08 11:00:00'),
    (1, 2.40, '2024-09-09 11:30:00'),
    (1, 2.60, '2024-09-10 12:00:00'),
    (1, 2.85, '2024-09-11 12:30:00'),
    (1, 3.00, '2024-09-12 13:00:00'),
    (1, 3.25, '2024-09-13 13:30:00'),
    (1, 3.50, '2024-09-14 14:00:00'),
    (1, 3.75, '2024-09-15 14:30:00'),
    (1, 4.00, '2024-09-16 15:00:00'),
    (2, 0.30, '2024-09-21 08:00:00'),
    (2, 0.65, '2024-09-22 08:30:00'),
    (2, 1.11, '2024-09-23 09:00:00'),
    (2, 1.20, '2024-09-24 09:15:00'),
    (2, 1.72, '2024-09-25 09:45:00'),
    (2, 1.79, '2024-09-26 10:00:00'),
    (2, 1.90, '2024-09-27 10:30:00'),
    (2, 2.15, '2024-09-28 11:00:00'),
    (2, 2.40, '2024-09-29 11:30:00'),
    (2, 2.60, '2024-09-20 12:00:00'),
    (2, 2.85, '2024-09-21 12:30:00'),
    (2, 3.00, '2024-09-22 13:00:00'),
    (2, 3.25, '2024-09-23 13:30:00'),
    (2, 3.50, '2024-09-24 14:00:00'),
    (2, 3.75, '2024-09-25 14:30:00'),
    (2, 4.00, '2024-09-26 15:00:00'),
    (23, 0.50, '2024-09-01 08:00:00'),
    (23, 0.75, '2024-09-02 08:30:00'),
    (23, 1.00, '2024-09-03 09:00:00'),
    (23, 1.20, '2024-09-04 09:15:00'),
    (23, 1.45, '2024-09-05 09:45:00'),
    (23, 1.70, '2024-09-06 10:00:00'),
    (23, 1.90, '2024-09-07 10:30:00'),
    (23, 2.15, '2024-09-08 11:00:00'),
    (23, 2.40, '2024-09-09 11:30:00'),
    (23, 2.60, '2024-09-10 12:00:00'),
    (23, 2.85, '2024-09-11 12:30:00'),
    (23, 3.00, '2024-09-12 13:00:00'),
    (23, 3.25, '2024-09-13 13:30:00'),
    (23, 3.50, '2024-09-14 14:00:00'),
    (23, 3.75, '2024-09-15 14:30:00'),
    (23, 4.00, '2024-09-16 15:00:00');
INSERT INTO SoilMeasurements (plant_id, value, time)
VALUES (1, 7.00, '2024-09-02 08:30:00'),
    (1, 7.02, '2024-09-03 09:00:00'),
    (1, 7.00, '2024-09-04 09:15:00'),
    (1, 7.34, '2024-09-05 09:45:00'),
    (1, 6.98, '2024-09-06 10:00:00'),
    (1, 7.00, '2024-09-07 10:30:00'),
    (1, 6.72, '2024-09-08 11:00:00'),
    (1, 7.11, '2024-09-09 11:30:00'),
    (1, 7.10, '2024-09-10 12:00:00'),
    (1, 6.84, '2024-09-11 12:30:00'),
    (1, 7.13, '2024-09-12 13:00:00'),
    (23, 7.00, '2024-09-02 08:30:00'),
    (23, 7.02, '2024-09-03 09:00:00'),
    (23, 7.00, '2024-09-04 09:15:00'),
    (23, 7.34, '2024-09-05 09:45:00'),
    (23, 6.98, '2024-09-06 10:00:00'),
    (23, 7.00, '2024-09-07 10:30:00'),
    (23, 6.72, '2024-09-08 11:00:00'),
    (23, 7.11, '2024-09-09 11:30:00'),
    (23, 7.10, '2024-09-10 12:00:00'),
    (23, 6.84, '2024-09-11 12:30:00'),
    (23, 7.13, '2024-09-12 13:00:00');
INSERT INTO LeafMeasurements (plant_id, value, time)
VALUES (1, 0, '2024-09-02 08:30:00'),
    (1, 0, '2024-09-03 09:00:00'),
    (1, 1, '2024-09-04 09:15:00'),
    (1, 1, '2024-09-05 09:45:00'),
    (1, 1, '2024-09-06 10:00:00'),
    (1, 2, '2024-09-07 10:30:00'),
    (1, 3, '2024-09-08 11:00:00'),
    (1, 3, '2024-09-09 11:30:00'),
    (1, 4, '2024-09-10 12:00:00'),
    (1, 6, '2024-09-11 12:30:00'),
    (1, 8, '2024-09-12 13:00:00'),
    (23, 0, '2024-09-02 08:30:00'),
    (23, 0, '2024-09-03 09:00:00'),
    (23, 1, '2024-09-04 09:15:00'),
    (23, 1, '2024-09-05 09:45:00'),
    (23, 1, '2024-09-06 10:00:00'),
    (23, 2, '2024-09-07 10:30:00'),
    (23, 3, '2024-09-08 11:00:00'),
    (23, 3, '2024-09-09 11:30:00'),
    (23, 4, '2024-09-10 12:00:00'),
    (23, 6, '2024-09-11 12:30:00'),
    (23, 8, '2024-09-12 13:00:00');
INSERT INTO FruitMeasurements (plant_id, value, time)
VALUES (1, 0, '2024-09-02 08:30:00'),
    (1, 0, '2024-09-03 09:00:00'),
    (1, 0, '2024-09-04 09:15:00'),
    (1, 0, '2024-09-05 09:45:00'),
    (1, 0, '2024-09-06 10:00:00'),
    (1, 0, '2024-09-07 10:30:00'),
    (1, 0, '2024-09-08 11:00:00'),
    (1, 2, '2024-09-09 11:30:00'),
    (1, 2, '2024-09-10 12:00:00'),
    (1, 3, '2024-09-11 12:30:00'),
    (1, 4, '2024-09-12 13:00:00'),
    (23, 0, '2024-07-06 10:00:00'),
    (23, 0, '2024-07-07 10:30:00'),
    (23, 0, '2024-07-08 11:00:00'),
    (23, 0, '2024-06-09 11:30:00'),
    (23, 0, '2024-06-10 12:00:00'),
    (23, 0, '2024-06-11 12:30:00'),
    (23, 0, '2024-09-12 13:00:00'),
    (23, 0, '2024-09-02 08:30:00'),
    (23, 0, '2024-09-03 09:00:00'),
    (23, 0, '2024-09-04 09:15:00'),
    (23, 0, '2024-09-05 09:45:00'),
    (23, 0, '2024-09-06 10:00:00'),
    (23, 0, '2024-09-07 10:30:00'),
    (23, 0, '2024-09-08 11:00:00'),
    (23, 0, '2024-09-09 11:30:00'),
    (23, 0, '2024-09-10 12:00:00'),
    (23, 0, '2024-09-11 12:30:00'),
    (23, 0, '2024-09-12 13:00:00');
INSERT INTO JournalEntries (plant_id, content, time)
VALUES (
        1,
        'This is an example journal entry for Tomato',
        '2024-09-26 15:00:00'
    ),
    (
        1,
        'Infested with disease- a brownish color now.',
        '2024-09-30 12:00:00'
    ),
    (
        1,
        'Tomato plant has been recovered and thriving!',
        '2024-10-06 18:30:00'
    ),
    (
        23,
        'This is an example journal entry for my Basil plant',
        '2024-09-26 15:00:00'
    ),
    (
        23,
        'Infested with disease- a brownish color now.',
        '2024-09-30 12:00:00'
    ),
    (
        23,
        'Finally treated it and it''s now recovered and thriving!',
        '2024-10-06 18:30:00'
    );